### ISSUE TITLE
群没了呀

### ISSUE THREAD

**Issue by moshuying** [henry-allen/select-house#1]

**Comment by henry-allen** [comment]
哈哈哈，是的，我删了，因为觉得对没啥价值了，你可以直接加我微信，
--------------原始邮件--------------
发件人："墨抒颖 ***@***.***&gt;;
发送时间：2022年1月4日(星期二) 晚上10:22
收件人："henry-allen/select-house" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[henry-allen/select-house] 群没了呀 (Issue #1)
-----------------------------------

 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by moshuying** [comment]
好吧
